config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do
    get "/users_by_email" => "users_by_emails#show", as: :users_by_email

    resources :favorites, only: [:create, :destroy]
  end

  get "/properties/search" => "properties/search#index"

  resources :properties, only: :show do
    resources :reservations, only: :new, controller: "properties/reservations"
  end

  resources :reservation_payments, only: :create

  resources :profiles, only: [:show, :update]

  resources :accounts, only: [:show, :update]
  
  resources :passwords, only: [:show, :update]

  resources :payments, only: :index

  put "/hostify/:user_id" => "hostify#update", as: :hostify

  namespace :host do
    get "/dashboard" => "dashboard#index", as: :dashboard

    resources :properties, only: [:new, :create]

    resources :payments, only: :index
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  include Countriable

  belongs_to :user

  has_one_attached :picture

  geocoded_by :address
  after_validation :geocode, if: -> { latitude.blank? && longitude.blank? }

  def address
    [state, country_name].compact.join(', ')
  end

  def full_name
    "#{first_name} #{last_name}".squish
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = Profile.find(params[:id])
    authorize @profile
  end

  def update
    @profile = Profile.find(params[:id])
    authorize @profile
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  private

  def profile_params
    params.require(:profile).permit(
      :first_name, :last_name, :address_1, :address_2, :city,
      :zip_code, :country_code, :picture
    )
  end
end

app/views/profiles/_sidebar.html.erb
<aside class="py-6 px-2 sm:px-6 lg:py-0 lg:px-0 lg:col-span-3 profiles-sidebar">
  <nav class="space-y-1">
    <%= link_to profile_path(current_user.profile), class: "text-gray-900 hover:text-gray-900 hover:bg-gray-50 group rounded-md px-3 py-2 flex items-center text-sm font-medium #{'active' if controller_name == "profiles"}" do %>
      <svg class="text-gray-400 group-hover:text-gray-500 flex-shrink-0 -ml-1 mr-3 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span class="truncate"> Profile </span>
    <% end %>

    <%= link_to account_path(current_user), class: "text-gray-900 hover:text-gray-900 hover:bg-gray-50 group rounded-md px-3 py-2 flex items-center text-sm font-medium #{'active' if controller_name == "accounts"}" do %>
      <!-- Heroicon name: outline/cog -->
      <svg class="text-gray-400 group-hover:text-gray-500 flex-shrink-0 -ml-1 mr-3 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>
      <span class="truncate"> Account </span>
    <% end %>

    <%= link_to password_path(current_user), class: "text-gray-900 hover:text-gray-900 hover:bg-gray-50 group rounded-md px-3 py-2 flex items-center text-sm font-medium #{'active' if controller_name == "passwords"}" do %>
      <!-- Heroicon name: outline/key -->
      <svg class="text-gray-400 group-hover:text-gray-500 flex-shrink-0 -ml-1 mr-3 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
      </svg>
      <span class="truncate"> Password </span>
    <% end %>

    <%= link_to payments_path, class: "text-gray-900 hover:text-gray-900 hover:bg-gray-50 group rounded-md px-3 py-2 flex items-center text-sm font-medium #{'active' if controller_name == "payments"}" do %>
      <!-- Heroicon name: outline/credit-card -->
      <svg class="text-gray-400 group-over:text-gray-500 flex-shrink-0 -ml-1 mr-3 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
      </svg>
      <span class="truncate"> Reservations / Payments </span>
    <% end %>
  </nav>
</aside>

app/views/profiles/show.html.erb
<div class="h-full bg-gray-100">
  <main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
    <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
      <%= render "profiles/sidebar" %>

      <!-- Payment details -->
      <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">
        <section aria-labelledby="payment-details-heading">
          <%= form_with model: @profile, local: true, url: profile_path(@profile) do |f| %>
            <div class="shadow sm:rounded-md sm:overflow-hidden">
              <div class="bg-white py-6 px-4 sm:p-6">
                <div>
                  <h2 id="payment-details-heading" class="text-lg leading-6 font-medium text-gray-900">Update Profile</h2>
                  <p class="mt-1 text-sm text-gray-500">Update your profile information.</p>
                </div>

                <div class="mt-6 grid grid-cols-4 gap-6">
                  <div class="col-span-4 sm:col-span-2">
                    <%= f.label :first_name, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :first_name, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4 sm:col-span-2">
                    <%= f.label :last_name, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :last_name, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4">
                    <%= f.label :address_1, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :address_1, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4">
                    <%= f.label :address_2, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :address_2, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4">
                    <%= f.label :city, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :city, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4 sm:col-span-2">
                    <%= f.label :zip_code, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :zip_code, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4 sm:col-span-2">
                    <%= f.label :country_code, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.country_select :country_code, { priority_countries: ["US", "CA"] }, class: "mt-1 block w-full bg-white border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-gray-900 focus:border-gray-900 sm:text-sm" %>
                  </div>

                  <div class="col-span-4 sm:col-span-2">
                    <%= f.label :picture, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.file_field :picture %>
                  </div>
                </div>
              </div>
              <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                <button type="submit" class="bg-gray-800 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900">Save</button>
              </div>
            </div>
          <% end %>
        </section>
      </div>
    </div>
  </main>
</div>