config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do
    get "/users_by_email" => "users_by_emails#show", as: :users_by_email

    resources :favorites, only: [:create, :destroy]
  end

  get "/properties/search" => "properties/search#index"

  resources :properties, only: :show do
    resources :reservations, only: :new, controller: "properties/reservations"
  end

  resources :reservation_payments, only: :create

  resources :profiles, only: [:show, :update]

  resources :accounts, only: [:show, :update]
  
  resources :passwords, only: [:show, :update]

  resources :payments, only: :index

  put "/hostify/:user_id" => "hostify#update", as: :hostify

  namespace :host do
    get "/dashboard" => "dashboard#index", as: :dashboard

    resources :properties, only: [:new, :create]

    resources :payments, only: :index
  end

end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  include Countriable

  CLEANING_FEE = 5_000.freeze
  CLEANING_FEE_MONEY = Money.new(CLEANING_FEE)
  SERVICE_FEE_PERCENTAGE = (0.08).freeze

  validates :name, presence: true
  validates :headline, presence: true
  validates :description, presence: true
  validates :address_1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country_code, presence: true

  monetize :price_cents, allow_nil: true

  geocoded_by :address
  after_validation :geocode, if: -> { latitude.blank? && longitude.blank? }

  belongs_to :user

  has_many_attached :images, dependent: :destroy

  has_many :reviews, as: :reviewable
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :reservations, dependent: :destroy
  has_many :payments, through: :reservations
  has_many :reserved_users, through: :reservations, source: :user

  scope :city, ->(city) { where("lower(city) like ?", "%#{city.downcase}%") }
  scope :country_code, ->(country_code) { where("lower(country_code) like ?", "%#{country_code.downcase}%") }
  scope :between_dates, -> (checkin, checkout) do
    joins(:reservations).
      where.not("reservations.checkin_date < ?", Date.strptime(checkin, Date::DATE_FORMATS[:us_short_date])).
      where.not("reservations.checkout_date > ?", Date.strptime(checkout, Date::DATE_FORMATS[:us_short_date]))
  end

  def address
    # [address_1, address_2, city, state, country_name].compact.join(', ')
    [state, country_name].compact.join(', ')
  end

  def default_image
    images.first
  end

  def favorited_by?(user)
    return if user.nil?

    favorited_users.include?(user)
  end

  def available_dates
    date_format = "%b %e"
    next_reservation = reservations.future_reservations.order(checkout_date: :desc).first
    return Date.tomorrow.strftime(date_format)..Date.today.end_of_year.strftime(date_format) if next_reservation.nil?

    next_reservation.checkout_date.strftime(date_format)..Date.today.end_of_year.strftime(date_format)
  end
end

app/controllers/host/dashboard_controller.rb
# frozen_string_literal: true

module Host
  class DashboardController < ApplicationController
    before_action :authenticate_user!

    def index
      authorize current_user, policy_class: HostPolicy
      @properties = current_user.properties
    end
  end
end

app/controllers/host/payments_controller.rb
# frozen_string_literal: true

module Host
  class PaymentsController < ApplicationController
    before_action :authenticate_user!

    def index
      authorize current_user, policy_class: HostPolicy
      @payments = current_user.receiving_payments
    end
  end
end

app/controllers/host/properties_controller.rb
# frozen_string_literal: true

module Host
  class PropertiesController < ApplicationController
    before_action :authenticate_user!

    def new
      authorize current_user, policy_class: HostPolicy
      @property = Property.new(user: current_user)
    end

    def create
      authorize current_user, policy_class: HostPolicy
      @property = current_user.properties.new(property_params)

      if @property.save
        redirect_to host_dashboard_path
      else
        render :new
      end
    end

    private

    def property_params
      params.require(:property).permit(
        :name, :headline, :description, :images, :address_1, :address_2, :city,
        :state, :zip_code, :country_code
      )
    end
  end
end

app/controllers/properties/reservations_controller.rb
# frozen_string_literal: true

module Properties
  class ReservationsController < ApplicationController
    before_action :authenticate_user!

    def new
      @property = Property.find(params[:property_id])
      @reservation = @property.reservations.new
      @checkin_date = new_reservation_params[:checkin_date]
      @checkout_date = new_reservation_params[:checkout_date]
      @subtotal = new_reservation_params[:subtotal]
      @cleaning_fee = new_reservation_params[:cleaning_fee]
      @service_fee = new_reservation_params[:service_fee]
      @total = new_reservation_params[:total]
    end

    private

    def new_reservation_params
      params.permit(
        :checkin_date, :checkout_date, :subtotal, :cleaning_fee,
        :service_fee, :total
      )
    end
  end
end

app/controllers/properties/search_controller.rb
# frozen_string_literal: true

module Properties
  class SearchController < ApplicationController
    def index
      @properties = Property.all

      if search_params[:city].present?
        @properties = @properties.city(search_params[:city])
      end

      if search_params[:country_code].present?
        @properties = @properties.country_code(search_params[:country_code])
      end

      properties_without_reservations = @properties.includes(:reservations).select { |property| property.reservations.size.zero? }

      if search_params[:checkin_date] && search_params[:checkout_date]
        @properties = @properties.between_dates(search_params[:checkin_date], search_params[:checkout_date])
      end

      @properties = Property.where(id: properties_without_reservations.map(&:id) + @properties.ids)
    end

    private

    def search_params
      params.permit(:city, :country_code, :checkin_date, :checkout_date)
    end
  end
end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  def show
    @property = Property.find(params[:id])
  end
end

app/helpers/property_helper.rb
module PropertyHelper
  def property_rating_percentage(property:, rating:)
    return 0 if property.reviews_count.zero?

    ((property.reviews.where(rating: rating).size.to_f / property.reviews_count) * 100).to_i
  end
end

app/views/host/properties/new.html.erb
<div class="h-full bg-gray-100">
  <main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
    <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
      <%= render "host/dashboard/sidebar" %>

      <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <%= form_with model: @property, url: host_properties_path, local: true do |f| %>
            <div class="shadow sm:rounded-md sm:overflow-hidden">
              <div class="bg-white py-6 px-4 space-y-6 sm:p-6">
                <div>
                  <h3 class="text-lg leading-6 font-medium text-gray-900">Add new Property</h3>
                  <p class="mt-1 text-sm text-gray-500">Use this form to create a new property for hosting.</p>
                </div>

                <div class="grid grid-cols-6 gap-6">
                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :name, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :headline, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :headline, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :description, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_area :description, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-4">
                    <%= f.label :images, "Image", class: "block text-sm font-medium text-gray-700" %>
                    <%= f.file_field :images %>
                  </div>

                  <div class="col-span-6">
                    <%= f.label :address_1, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :address_1, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6">
                    <%= f.label :address_2, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :address_2, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-6 lg:col-span-2">
                    <%= f.label :city, class: "block text-sm font-medium text-gray-700"  %>
                    <%= f.text_field :city, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                    <%= f.label :state, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :state, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                    <%= f.label :zip_code, class: "block text-sm font-medium text-gray-700" %>
                    <%= f.text_field :zip_code, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>

                  <div class="col-span-6 sm:col-span-3">
                    <%= f.label :country_code, "Country", class: "block text-sm font-medium text-gray-700" %>
                    <%= f.country_select :country_code, { priority_countries: ["US", "CA"] }, class: "mt-1 block w-full bg-white border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                  </div>
                </div>
              </div>
              <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                <button type="submit" class="bg-indigo-600 border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Save</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</div>