config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do
    get "/users_by_email" => "users_by_emails#show", as: :users_by_email

    resources :favorites, only: [:create, :destroy]
  end

  get "/properties/search" => "properties/search#index"

  resources :properties, only: :show do
    resources :reservations, only: :new, controller: "properties/reservations"
  end

  resources :reservation_payments, only: :create

  resources :profiles, only: [:show, :update]

  resources :accounts, only: [:show, :update]
  
  resources :passwords, only: [:show, :update]

  resources :payments, only: :index

  put "/hostify/:user_id" => "hostify#update", as: :hostify

  namespace :host do
    get "/dashboard" => "dashboard#index", as: :dashboard

    resources :properties, only: [:new, :create]

    resources :payments, only: :index
  end

end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  include Countriable

  CLEANING_FEE = 5_000.freeze
  CLEANING_FEE_MONEY = Money.new(CLEANING_FEE)
  SERVICE_FEE_PERCENTAGE = (0.08).freeze

  validates :name, presence: true
  validates :headline, presence: true
  validates :description, presence: true
  validates :address_1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country_code, presence: true

  monetize :price_cents, allow_nil: true

  geocoded_by :address
  after_validation :geocode, if: -> { latitude.blank? && longitude.blank? }

  belongs_to :user

  has_many_attached :images, dependent: :destroy

  has_many :reviews, as: :reviewable
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :reservations, dependent: :destroy
  has_many :payments, through: :reservations
  has_many :reserved_users, through: :reservations, source: :user

  scope :city, ->(city) { where("lower(city) like ?", "%#{city.downcase}%") }
  scope :country_code, ->(country_code) { where("lower(country_code) like ?", "%#{country_code.downcase}%") }
  scope :between_dates, -> (checkin, checkout) do
    joins(:reservations).
      where.not("reservations.checkin_date < ?", Date.strptime(checkin, Date::DATE_FORMATS[:us_short_date])).
      where.not("reservations.checkout_date > ?", Date.strptime(checkout, Date::DATE_FORMATS[:us_short_date]))
  end

  def address
    # [address_1, address_2, city, state, country_name].compact.join(', ')
    [state, country_name].compact.join(', ')
  end

  def default_image
    images.first
  end

  def favorited_by?(user)
    return if user.nil?

    favorited_users.include?(user)
  end

  def available_dates
    date_format = "%b %e"
    next_reservation = reservations.future_reservations.order(checkout_date: :desc).first
    return Date.tomorrow.strftime(date_format)..Date.today.end_of_year.strftime(date_format) if next_reservation.nil?

    next_reservation.checkout_date.strftime(date_format)..Date.today.end_of_year.strftime(date_format)
  end
end

app/controllers/host/properties_controller.rb
# frozen_string_literal: true

module Host
  class PropertiesController < ApplicationController
    before_action :authenticate_user!

    def new
      authorize current_user, policy_class: HostPolicy
      @property = Property.new(user: current_user)
    end

    def create
      authorize current_user, policy_class: HostPolicy
      @property = current_user.properties.new(property_params)

      if @property.save
        redirect_to host_dashboard_path
      else
        render :new
      end
    end

    private

    def property_params
      params.require(:property).permit(
        :name, :headline, :description, :images, :address_1, :address_2, :city,
        :state, :zip_code, :country_code
      )
    end
  end
end

app/controllers/properties/reservations_controller.rb
# frozen_string_literal: true

module Properties
  class ReservationsController < ApplicationController
    before_action :authenticate_user!

    def new
      @property = Property.find(params[:property_id])
      @reservation = @property.reservations.new
      @checkin_date = new_reservation_params[:checkin_date]
      @checkout_date = new_reservation_params[:checkout_date]
      @subtotal = new_reservation_params[:subtotal]
      @cleaning_fee = new_reservation_params[:cleaning_fee]
      @service_fee = new_reservation_params[:service_fee]
      @total = new_reservation_params[:total]
    end

    private

    def new_reservation_params
      params.permit(
        :checkin_date, :checkout_date, :subtotal, :cleaning_fee,
        :service_fee, :total
      )
    end
  end
end

app/controllers/properties/search_controller.rb
# frozen_string_literal: true

module Properties
  class SearchController < ApplicationController
    def index
      @properties = Property.all

      if search_params[:city].present?
        @properties = @properties.city(search_params[:city])
      end

      if search_params[:country_code].present?
        @properties = @properties.country_code(search_params[:country_code])
      end

      properties_without_reservations = @properties.includes(:reservations).select { |property| property.reservations.size.zero? }

      if search_params[:checkin_date] && search_params[:checkout_date]
        @properties = @properties.between_dates(search_params[:checkin_date], search_params[:checkout_date])
      end

      @properties = Property.where(id: properties_without_reservations.map(&:id) + @properties.ids)
    end

    private

    def search_params
      params.permit(:city, :country_code, :checkin_date, :checkout_date)
    end
  end
end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  def show
    @property = Property.find(params[:id])
  end
end

app/helpers/property_helper.rb
module PropertyHelper
  def property_rating_percentage(property:, rating:)
    return 0 if property.reviews_count.zero?

    ((property.reviews.where(rating: rating).size.to_f / property.reviews_count) * 100).to_i
  end
end

app/views/properties/_product_info.html.erb
<!-- Product info -->
<div class="max-w-2xl mx-auto pt-10 pb-16 px-4 sm:px-6 lg:max-w-7xl lg:pt-16 lg:pb-24 lg:px-8 lg:grid lg:grid-cols-3 lg:grid-rows-[auto,auto,1fr] lg:gap-x-8">
  <div class="lg:col-span-2 lg:border-r lg:border-gray-200 lg:pr-8">
    <h1 class="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">Entire rental unit hosted by Fliphaus</h1>
  </div>

  <!-- Reservation Component -->
  <div
    class="mt-4 lg:mt-0 lg:row-span-3"
    data-controller="reservation-component"
    data-default-checkin-date="<%= Date.tomorrow.to_formatted_s(:us_short_date) %>"
    data-default-checkout-date="<%= (Date.tomorrow + 1.day).to_formatted_s(:us_short_date) %>"
    data-nightly-price="<%= humanized_money(@property.price) %>"
    data-service-fee-percentage="<%= Property::SERVICE_FEE_PERCENTAGE %>"
    data-cleaning-fee="<%= humanized_money(Property::CLEANING_FEE_MONEY) %>"
  >
    <div class="mt-10 lg:mt-0">
      <h2 class="text-2xl font-medium text-gray-900"><%= humanized_money_with_symbol(@property.price) %> night</h2>

      <div class="isolate -space-y-px rounded-md shadow-sm mt-6">
        <div class="relative border border-gray-300 rounded-md rounded-b-none px-3 py-2 focus-within:z-10 focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
          <label for="name" class="block text-xs font-medium text-gray-900 uppercase">Check-in</label>
          <input
            type="text"
            name="name"
            id="name"
            class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm"
            placeholder="11/30/2022"
            data-reservation-component-target="checkin"
          >
        </div>
        <div class="relative border border-gray-300 rounded-md rounded-t-none px-3 py-2 focus-within:z-10 focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600">
          <label for="job-title" class="block text-xs font-medium text-gray-900 uppercase">Checkout</label>
          <input
            type="text"
            name="job-title"
            id="job-title"
            class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm"
            placeholder="12/7/2022"
            data-reservation-component-target="checkout"
          >
        </div>
      </div>

      <div class="bg-white mt-6">
        <div class="divide-y divide-gray-200">
        </div>
        <dl class="space-y-6">
          <div class="flex items-center justify-between">
            <dt class="text-sm"><%= humanized_money_with_symbol(@property.price) %> x <span data-reservation-component-target="numOfNights">0</span> nights</dt>
            <dd class="text-sm font-medium text-gray-900">$<span data-reservation-component-target="nightlyTotal">0.00</span></dd>
          </div>
          <div class="flex items-center justify-between">
            <dt class="text-sm">Cleaning fee</dt>
            <dd class="text-sm font-medium text-gray-900"><%= humanized_money_with_symbol Property::CLEANING_FEE_MONEY %></dd>
          </div>
          <div class="flex items-center justify-between">
            <dt class="text-sm">Service fee</dt>
            <dd class="text-sm font-medium text-gray-900">$<span data-reservation-component-target="serviceFee">0.00</span></dd>
          </div>
          <div class="flex items-center justify-between border-t border-gray-200 pt-6">
            <dt class="text-base font-medium">Total</dt>
            <dd class="text-base font-medium text-gray-900">$<span data-reservation-component-target="total">0.00</span></dd>
          </div>
        </dl>

        <div class="pt-6">
          <button
            data-submit-url="<%= new_property_reservation_path(@property) %>"
            data-action="reservation-component#submitReservationComponent"
            type="submit"
            class="w-full bg-indigo-600 border border-transparent rounded-md shadow-sm py-3 px-4 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-indigo-500">Confirm order
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="py-10 lg:pt-6 lg:pb-16 lg:col-start-1 lg:col-span-2 lg:border-r lg:border-gray-200 lg:pr-8">
    <!-- Description and details -->
    <div>
      <h3 class="sr-only">Description</h3>

      <div class="space-y-6">
        <p class="text-base text-gray-900"><%= truncate @property.description, length: 500 %></p>

        <% if @property.description.length > 500 %>
          <%= link_to "Show more >", "", class: "text-lg font-medium underline", data: { action: "property#readDescription" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/modal", modal_trigger_id: "property-description-trigger", modal_content: "properties/property_description", content_params: { property: @property } %>

app/views/properties/_property.html.erb
<%= link_to property_path(property) do %>
  <li
    class="relative"
    data-geolocation-target="property"
    data-google-maps-target="property"
    data-latitude="<%= property.latitude %>"
    data-longitude="<%= property.longitude %>"
  >
    <div class="group block w-full aspect-w-10 aspect-h-7 rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offset-gray-100 focus-within:ring-indigo-500 overflow-hidden">
      <%= image_tag property.default_image, class: "object-cover pointer-events-none group-hover:opacity-75" %>
      <button type="button" class="absolute inset-0 focus:outline-none">
        <span class="sr-only">View details for IMG_4985.HEIC</span>
      </button>

      <div class="flex flex-row-reverse p-2">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-8 w-8 cursor-pointer"
          data-controller="favorites"
          data-user-logged-in="<%= user_signed_in? %>"
          data-user-id="<%= current_user&.id %>"
          data-property-id="<%= property.id %>"
          data-favorite-id="<%= property.favorites.find_by(user: current_user)&.id %>"
          data-favorited="<%= property.favorited_by?(current_user) %>"
          data-action="click->favorites#favorite"
          data-favorited-color="red"
          data-unfavorited-color="#ced4da"
          fill="<%= property.favorited_by?(current_user) ? 'red' : '#ced4da' %>"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="2"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg>
      </div>
    </div>
    <p class="mt-2 block text-sm font-medium text-gray-900 truncate pointer-events-none"><%= property.city %>, <%= property.state %> <%= property.country_name %></p>
    <p class="block text-sm font-medium text-gray-500 pointer-events-none text-black">
      <%= property.average_rating.round(2) %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block relative" viewBox="0 0 20 20" fill="currentColor" style="bottom: 2px;">
        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
      </svg>
    </p>
    <p data-distance-away class="block text-sm font-medium text-gray-500 pointer-events-none"></p>
    <p class="block text-sm font-medium text-gray-500 pointer-events-none"><%= property.available_dates.first %> - <%= property.available_dates.last %></p>
    <p class="block text-sm font-medium text-gray-500 pointer-events-none"><span class="text-black"><%= humanized_money_with_symbol(property.price) %></span> per night</p>
  </li>
<% end %>

app/views/properties/_property_description.html.erb
<div>
  <div class="flex mb-5">
    <div class="flex-none cursor-pointer" data-modal-target="closeButton">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
      </svg>
    </div>
  </div>

  <div>
    <p class="text-2xl font-medium mb-4">About this space</p>

    <div>
      <%= content_params[:property].description %>
    </div>
  </div>
</div>

app/views/properties/_reviews.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="bg-white">
  <div class="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:py-32 lg:px-8 lg:grid lg:grid-cols-12 lg:gap-x-8">
    <div class="lg:col-span-4">
      <h2 class="text-2xl font-extrabold tracking-tight text-gray-900">Customer Reviews</h2>

      <div class="mt-3 flex items-center">
        <div>
          <div class="flex items-center">
            <%
              property_star_classes = ["text-gray-300", "text-gray-300", "text-gray-300", "text-gray-300", "text-gray-300"]

              (@property.average_rating.round(0)).times do |i|
                property_star_classes[i] = "text-yellow-400"
              end
            %>

            <% property_star_classes.each do |star_class| %>
              <svg class="flex-shrink-0 h-5 w-5 <%= star_class %>" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
              </svg>
            <% end %>
          </div>
          <p class="sr-only"><%= @property.average_rating.round(0) %> out of 5 stars</p>
        </div>
        <p class="ml-2 text-sm text-gray-900">Based on <%= @property.reviews_count %> reviews</p>
      </div>

      <div class="mt-6">
        <h3 class="sr-only">Review data</h3>

        <dl class="space-y-3">
          <% 5.downto(1) do |n| %>
            <div class="flex items-center text-sm">
              <dt class="flex-1 flex items-center">
              <p class="w-3 font-medium text-gray-900"><%= n %><span class="sr-only"> star reviews</span></p>
              <div aria-hidden="true" class="ml-1 flex-1 flex items-center">
                <!-- Heroicon name: solid/star -->
                <svg class="flex-shrink-0 h-5 w-5 text-yellow-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                </svg>

                <div class="ml-3 relative flex-1">
                  <div class="h-3 bg-gray-100 border border-gray-200 rounded-full"></div>

                  <div style="width: calc(<%= @property.reviews.where(rating: n).size %> / <%= @property.reviews_count %> * 100%)" class="absolute inset-y-0 bg-yellow-400 border border-yellow-400 rounded-full"></div>
                </div>
              </div>
              </dt>
              <dd class="ml-3 w-10 text-right tabular-nums text-sm text-gray-900"><%= property_rating_percentage(property: @property, rating: n) %>%</dd>
            </div>
          <% end %>
        </dl>
      </div>
    </div>

    <div class="mt-16 lg:mt-0 lg:col-start-6 lg:col-span-7">
      <h3 class="sr-only">Recent reviews</h3>

      <div class="flow-root">
        <div class="-my-12 divide-y divide-gray-200">
          <% @property.reviews.includes(user: :profile).each do |review| %>
            <div class="py-12">
              <div class="flex items-center">
                <%= image_tag review.user.profile.picture, class: "h-12 w-12 rounded-full", alt: review.user.full_name %>
                <div class="ml-4">
                  <h4 class="text-sm font-bold text-gray-900"><%= review.user.full_name %></h4>
                  <div class="mt-1 flex items-center">
                    <%
                      review_star_classes = ["text-gray-300", "text-gray-300", "text-gray-300", "text-gray-300", "text-gray-300"]

                      review.rating.times do |i|
                        review_star_classes[i] = "text-yellow-400"
                      end
                    %>

                    <% review_star_classes.each do |star_class| %>
                      <svg class="<%= star_class %> h-5 w-5 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                      </svg>
                    <% end %>
                    <!--
                      Heroicon name: solid/star

                      Active: "text-yellow-400", Default: "text-gray-300"
                    -->
                  </div>
                  <p class="sr-only"><%= review.rating %> out of 5 stars</p>
                </div>
              </div>

              <div class="mt-4 space-y-6 text-base italic text-gray-600">
                <p><%= review.body %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/properties/_search_form.html.erb
<div
  data-controller="properties-search"
  data-default-checkin-date="<%= Date.tomorrow.to_formatted_s(:us_short_date) %>"
  data-default-checkout-date="<%= (Date.tomorrow + 1.day).to_formatted_s(:us_short_date) %>"
>
  <div class="flex mb-5">
    <div class="flex-none cursor-pointer" data-modal-target="closeButton">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
      </svg>
    </div>
  </div>

  <div>
    <%= form_with(
      url: properties_search_path,
      method: :get,
      local: true,
      class: "space-y-8 divide-y divide-gray-200") do |f|
    %>
      <div class="space-y-8 divide-y divide-gray-200 sm:space-y-5">
        <div class="space-y-6 sm:space-y-5">
          <div>
            <h3 class="text-lg leading-6 font-medium text-gray-900">Search for Property</h3>
          </div>
          <div class="space-y-6 sm:space-y-5">
            <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
              <%= f.label :city, class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
              <div class="mt-1 sm:mt-0 sm:col-span-2">
                <%= f.text_field :city, class: "max-w-lg block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md" %>
              </div>
            </div>

            <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
              <%= f.label :country_code, "Country", class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
              <div class="mt-1 sm:mt-0 sm:col-span-2">
                <%= f.country_select :country_code, { priority_countries: ["US", "CA"] }, class: "max-w-lg block focus:ring-indigo-500 focus:border-indigo-500 w-full shadow-sm sm:max-w-xs sm:text-sm border-gray-300 rounded-md" %>
              </div>
            </div>

            <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
              <%= f.label :checkin_date, "Check in", class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
              <div class="mt-1 sm:mt-0 sm:col-span-2">
                <%= f.text_field :checkin_date, class: "block max-w-lg w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md", data: { "properties-search-target": "checkin" }, required: true  %>
              </div>
            </div>

            <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
              <%= f.label :checkout_date, "Check out", class: "block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2" %>
              <div class="mt-1 sm:mt-0 sm:col-span-2">
                <%= f.text_field :checkout_date, class: "max-w-lg block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md", data: { "properties-search-target": "checkout" }, required: true %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="pt-5">
        <div class="flex justify-end">
          <%= f.submit "Search", class: "cursor-pointer ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", style: "margin-right: 26px" %>
        </div>
      </div>
    <% end %>
  </div>
</div>